CREATE TABLE [dbo].[tblUsers]
(
	[UserId] INT NOT NULL IDENTITY, 
	[Username] VARCHAR(50) NOT NULL,
	[Password] VARCHAR(500) NOT NULL,
	[PasswordSalt] VARCHAR(500) NOT NULL,
	[FirstName] VARCHAR(50) NOT NULL,
	[MiddleName] VARCHAR(50),
	[LastName] VARCHAR(50) NOT NULL,
	[Mobile] VARCHAR(15) NOT NULL,
	[Email] VARCHAR(50),
	[Gender] VARCHAR(10),
	[MaritalStatus] VARCHAR(10),
	[ProfilePic] VARCHAR(100),
	[AddressLine1] VARCHAR(60),
	[AddressLine2] VARCHAR(60),
	[City] VARCHAR(60),
	[State] VARCHAR(100),
	[Pincode] VARCHAR(11),
	[Landmark] VARCHAR(60),
	[Latitude] VARCHAR(100),
	[Longtitude] VARCHAR(100),
	[Occupation] VARCHAR(100),
	[BirthDate] DATETIME,
	[RoleId] INT NOT NULL,
	[IsActive] BIT NOT NULL,
    CONSTRAINT [PK_tblUsers] PRIMARY KEY ([UserId]), 
    CONSTRAINT [FK_tblUsers_tblRoles] FOREIGN KEY ([RoleId]) REFERENCES [tblRoles]([RoleId]) 
)
